name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          submodules: 'true'
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build

  macos-build-test:
    name: macos build test
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          submodules: 'true'
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build
